version: '3.8'

services:
  flagd:
    image: ghcr.io/open-feature/flagd:latest
    command: start --uri file:/etc/flagd/flags.json
    ports:
      - "8013:8013"
    volumes:
      - ./:/etc/flagd/
    stdin_open: true
    tty: true
